name: spring-app-advisor-workflow
on:
  push:
    branches:
      - 'advisor-demo'
jobs:
  app_advisor_job:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Upgrade Spring Application Dependencies
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'
      - name: Run Spring Application Advisor
        uses: dbeauregard/spring-app-advisor-action@v1.1.5
        with:
          artifactory_token: ${{ secrets.ARTIFACTORYTOKEN }}
          git_token: ${{ secrets.GITHUB_TOKEN }}
          app_advisor_server: ${{ vars.SAA_SERVER}}
          email: ${{ vars.EMAIL }}
          build_tool: gradlew
      - name: find stuff
        if: always()
        run: |
          pwd
          ls
          ls .advisor
          ls -la errors
          ls -la /home/runner/work
          ls -la /home/runner/work/spring-petclinic-saa
          ls -la /home/runner/work/spring-petclinic-saa/spring-petclinic-saa
          ls -la /usr/local/bin
      - name: Upload SAA Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SAA Logs
          path: .advisor/**/*

        